name: flutter_grad_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  autocomplete_textfield: ^2.0.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_custom_carousel_slider: ^1.2.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  simple_gradient_text: ^1.3.0
  syncfusion_flutter_datepicker: ^23.2.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application
  fonts:
    - family: monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf

    - family: josefinSans
      fonts:
        - asset: assets/fonts/JosefinSans/static/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans/static/JosefinSans-Bold.ttf

    - family: JosefinSans_Bold
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Bold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: JosefinSans_Regular
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Regular.ttf

    - family: JosefinSans_Light
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Light.ttf

    - family: JosefinSans_Italic
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-Italic.ttf

    - family: JosefinSans_SemiBold
      fonts:
        - asset: assets/fonts/Josefin_Sans/static/JosefinSans-SemiBold.ttf

    - family: JosefinSans_Bold
      fonts:
        - asset: assets/fonts/static/JosefinSans-Bold.ttf

    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: JosefinSans_Regular
      fonts:
        - asset: assets/fonts/static/JosefinSans-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
